---
vpc: vpc-034e84993db363bcd
ecs_subnets: # required: at least 2 subnets
  - subnet-0e4e445b17b8265a0
  - subnet-013240d793312106f
elb_subnets: # defaults to same subnets as ecs_subnets when not set
  - subnet-0e4e445b17b8265a0
  - subnet-013240d793312106f

# Optional additional existing security group ids to add on top of the ones created by ufo.
# elb_security_groups:
#   - sg-aaa
# ecs_security_groups:
#   - sg-bbb
#   - sg-ccc
