# More info: http://ufoships.com/docs/ufo-settings/
# The base config is treated special. It gets included the other environments automatically.
# Yaml also directly supports merging with & and <<* syntax but doing it automatically
# for a cleaner syntax.
base:
  image: 536766270177.dkr.ecr.us-west-2.amazonaws.com/demo/sinatra
  # clean_keep: 30
  # ecr_keep: 30
  # network_profile: default # .ufo/settings/network/default.yml file
  # cfn_profile: default # .ufo/settings/cfn/default.yml file
  # If you want to have prettier name set for the ECS service name
  # There are some cavaets with this. Updating properties on resources that require
  # replacment might not work. For example, adding and removing a load balancer.
  # In these cases, you must delete the entire ecs service and recreate it.
  stack_naming: append_env

development:
  # cluster: development
  # The aws_profile tightly binds UFO_ENV to AWS_PROFILE and vice-versa.
  # aws_profile: dev_profile

production:
  # cluster: production
  # The aws_profile tightly binds UFO_ENV to AWS_PROFILE and vice-versa.
  # aws_profile: prod_profile
