# Build Specification Reference for CodeBuild: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
  build:
    commands:
      - .cody/scripts/ssm.sh $ECS_SERVICE $DOCKER_CONTAINER $S3_PATH
